;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2010-1-11 19:36:03

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1035=关于zLib.html	; about zLib.js
IDH_1074=选择器\class.html	; .class
IDH_1075=选择器\createHTMLTag.html	; *tagName
IDH_1076=选择器\id,tagName.html	; id,tagName
IDH_1077=选择器\id.html	; #id
IDH_1078=选择器\object,tagName.html	; object,tagName
IDH_1079=选择器\object.html	; object
IDH_1080=选择器\tagName.html	; tagName
IDH_1041=属性\class\addClass(classname).html	; addClass(classname)
IDH_1042=属性\class\hasClass(classname).html	; hasClass(classname)
IDH_1043=属性\class\removeClass(classname).html	; removeClass(classname)
IDH_1044=属性\Html\html([val]).html	; html([val])
IDH_1045=属性\属性\attr(name,[value]).html	; attr(name,[value])
IDH_1046=属性\属性\attrs(pros).html	; attrs(pros)
IDH_1047=属性\属性\removeAttr(name).html	; removeAttr(name)
IDH_1002=CSS\css\getCss(property).html	; getCss(property)
IDH_1003=CSS\css\setCss(styles).html	; setCss(styles)
IDH_1004=CSS\css\setStyle(property,value).html	; setStyle(property,value)
IDH_1017=CSS\尺寸\getHeight().html	; getHeight()
IDH_1018=CSS\尺寸\getWidth().html	; getWidth()
IDH_1019=CSS\尺寸\zlib.static.pageHeight().html	; zlib.static.pageHeight()
IDH_1020=CSS\尺寸\zlib.static.pageWidth().html	; zlib.static.pageWidth()
IDH_1021=CSS\尺寸\zlib.static.windowHeight().html	; zlib.static.windowHeight()
IDH_1022=CSS\尺寸\zlib.static.windowWidth().html	; zlib.static.windowWidth()
IDH_1015=CSS\动态样式表\addStyleSheet(url,[_media]).html	; zlib.static.addStyleSheet(url,[ media])
IDH_1016=CSS\动态样式表\removeStyleSheet(url).html	; zlib.static.removeStyleSheet(url)
IDH_1023=CSS\透明度\setOpacity(level).html	; setOpacity(level)
IDH_1005=CSS\位置\gapsX().html	; gapsX()
IDH_1006=CSS\位置\gapsY().html	; gapsY()
IDH_1007=CSS\位置\parentX().html	; parentX()
IDH_1008=CSS\位置\parentY().html	; parentY()
IDH_1009=CSS\位置\zlib.static.getElementX(e).html	; zlib.static.getElementX(e)
IDH_1010=CSS\位置\zlib.static.getElementY(e).html	; zlib.static.getElementY(e)
IDH_1011=CSS\位置\zlib.static.getX(e).html	; zlib.static.getX(e)
IDH_1012=CSS\位置\zlib.static.getY(e).html	; zlib.static.getY(e)
IDH_1013=CSS\位置\zlib.static.scrollX().html	; zlib.static.scrollX()
IDH_1014=CSS\位置\zlib.static.scrollY().html	; zlib.static.scrollY()
IDH_1024=CSS\颜色值格式转换\zlib.static.colorToNormal(str).html	; zlib.static.colorToNormal(str)
IDH_1025=CSS\颜色值格式转换\zlib.static.colorToRGB(str).html	; zlib.static.colorToRGB(str)
IDH_1036=基本\each(callback).html	; each(callback)
IDH_1037=基本\getClass(index).html	; getClass(index)
IDH_1038=基本\getDom([index]).html	; getDom([index])
IDH_1039=基本\one(filter,callback).html	; one(filter,callback)
IDH_1040=基本\size().html	; size()
IDH_1064=检测数据类型\zlib.static.getType(obj).html	; zlib.static.getType(obj)
IDH_1065=简单动画\fadeIn([speed],[callback]).html	; fadeIn([speed],[callback])
IDH_1066=简单动画\fadeOut([speed],[callback]).html	; fadeOut([speed],[callback])
IDH_1067=简单动画\fadeToggle([speed],[callback]).html	; fadeToggle([speed],[callback])
IDH_1068=简单动画\hide([speed],[callback]).html	; hide([speed],[callback])
IDH_1069=简单动画\show([speed],[callback]).html	; show([speed],[callback])
IDH_1070=简单动画\slideDown([speed],[callback]).html	; slideDown([speed],[callback])
IDH_1071=简单动画\slideToggle([speed],[callback]).html	; slideToggle([speed],[callback])
IDH_1072=简单动画\slideUp([speed],[callback]).html	; slideUp([speed],[callback])
IDH_1073=简单动画\toggle([speed],[callback]).html	; toggle([speed],[callback])
IDH_1059=文档处理\查找元素\first().html	; first()
IDH_1060=文档处理\查找元素\last().html	; last()
IDH_1061=文档处理\查找元素\next().html	; next()
IDH_1062=文档处理\查找元素\parent([num]).html	; parent([num])
IDH_1063=文档处理\查找元素\prev().html	; prev()
IDH_1054=文档处理\复制元素\clone().html	; clone()
IDH_1048=文档处理\内部插入\append(para).html	; append(para)
IDH_1049=文档处理\内部插入\appendTo(para).html	; appendTo(para)
IDH_1050=文档处理\内部插入\prepend(para).html	; prepend(para)
IDH_1051=文档处理\内部插入\prependTo(para).html	; prependTo(para)
IDH_1052=文档处理\删除\empty().html	; empty()
IDH_1053=文档处理\删除\remove().html	; remove()
IDH_1055=文档处理\外部插入\after(para).html	; after(para)
IDH_1056=文档处理\外部插入\before(para).html	; before(para)
IDH_1057=文档处理\外部插入\insertAfter(para).html	; insertAfter(para)
IDH_1058=文档处理\外部插入\insertBefore(para).html	; insertBefore(para)
IDH_1033=事件\访问键盘\zlib.static.getKey(e).html	; zlib.static.getKey(e)
IDH_1034=事件\默认动作\zlib.static.preventDefault(e).html	; zlib.static.preventDefault(e)
IDH_1032=事件\目标元素\zlib.static.getTarget(e).html	; zlib.static.getTarget(e)
IDH_1029=事件\事件绑定\bindEvent(eventType,callback).html	; bindEvent(eventType,callback)
IDH_1030=事件\事件绑定\isMouseLeaveOrEnter(e).html	; isMouseLeaveOrEnter(e)
IDH_1031=事件\事件绑定\mouseHover(fn1,fn2).html	; mouseHover(fn1,fn2)
IDH_1028=事件\事件冒泡\zlib.static.stopBubble(e).html	; zlib.static.stopBubble(e)
IDH_1000=ajax\zlib.static.ajax(options).html	; zlib.static.ajax(options)
