;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2010-1-11 19:36:03

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1035	1035	; about zLib.js 关于zLib.html
#define IDH_1074	1074	; .class 选择器\class.html
#define IDH_1075	1075	; *tagName 选择器\createHTMLTag.html
#define IDH_1076	1076	; id,tagName 选择器\id,tagName.html
#define IDH_1077	1077	; #id 选择器\id.html
#define IDH_1078	1078	; object,tagName 选择器\object,tagName.html
#define IDH_1079	1079	; object 选择器\object.html
#define IDH_1080	1080	; tagName 选择器\tagName.html
#define IDH_1041	1041	; addClass(classname) 属性\class\addClass(classname).html
#define IDH_1042	1042	; hasClass(classname) 属性\class\hasClass(classname).html
#define IDH_1043	1043	; removeClass(classname) 属性\class\removeClass(classname).html
#define IDH_1044	1044	; html([val]) 属性\Html\html([val]).html
#define IDH_1045	1045	; attr(name,[value]) 属性\属性\attr(name,[value]).html
#define IDH_1046	1046	; attrs(pros) 属性\属性\attrs(pros).html
#define IDH_1047	1047	; removeAttr(name) 属性\属性\removeAttr(name).html
#define IDH_1002	1002	; getCss(property) CSS\css\getCss(property).html
#define IDH_1003	1003	; setCss(styles) CSS\css\setCss(styles).html
#define IDH_1004	1004	; setStyle(property,value) CSS\css\setStyle(property,value).html
#define IDH_1017	1017	; getHeight() CSS\尺寸\getHeight().html
#define IDH_1018	1018	; getWidth() CSS\尺寸\getWidth().html
#define IDH_1019	1019	; zlib.static.pageHeight() CSS\尺寸\zlib.static.pageHeight().html
#define IDH_1020	1020	; zlib.static.pageWidth() CSS\尺寸\zlib.static.pageWidth().html
#define IDH_1021	1021	; zlib.static.windowHeight() CSS\尺寸\zlib.static.windowHeight().html
#define IDH_1022	1022	; zlib.static.windowWidth() CSS\尺寸\zlib.static.windowWidth().html
#define IDH_1015	1015	; zlib.static.addStyleSheet(url,[ media]) CSS\动态样式表\addStyleSheet(url,[_media]).html
#define IDH_1016	1016	; zlib.static.removeStyleSheet(url) CSS\动态样式表\removeStyleSheet(url).html
#define IDH_1023	1023	; setOpacity(level) CSS\透明度\setOpacity(level).html
#define IDH_1005	1005	; gapsX() CSS\位置\gapsX().html
#define IDH_1006	1006	; gapsY() CSS\位置\gapsY().html
#define IDH_1007	1007	; parentX() CSS\位置\parentX().html
#define IDH_1008	1008	; parentY() CSS\位置\parentY().html
#define IDH_1009	1009	; zlib.static.getElementX(e) CSS\位置\zlib.static.getElementX(e).html
#define IDH_1010	1010	; zlib.static.getElementY(e) CSS\位置\zlib.static.getElementY(e).html
#define IDH_1011	1011	; zlib.static.getX(e) CSS\位置\zlib.static.getX(e).html
#define IDH_1012	1012	; zlib.static.getY(e) CSS\位置\zlib.static.getY(e).html
#define IDH_1013	1013	; zlib.static.scrollX() CSS\位置\zlib.static.scrollX().html
#define IDH_1014	1014	; zlib.static.scrollY() CSS\位置\zlib.static.scrollY().html
#define IDH_1024	1024	; zlib.static.colorToNormal(str) CSS\颜色值格式转换\zlib.static.colorToNormal(str).html
#define IDH_1025	1025	; zlib.static.colorToRGB(str) CSS\颜色值格式转换\zlib.static.colorToRGB(str).html
#define IDH_1036	1036	; each(callback) 基本\each(callback).html
#define IDH_1037	1037	; getClass(index) 基本\getClass(index).html
#define IDH_1038	1038	; getDom([index]) 基本\getDom([index]).html
#define IDH_1039	1039	; one(filter,callback) 基本\one(filter,callback).html
#define IDH_1040	1040	; size() 基本\size().html
#define IDH_1064	1064	; zlib.static.getType(obj) 检测数据类型\zlib.static.getType(obj).html
#define IDH_1065	1065	; fadeIn([speed],[callback]) 简单动画\fadeIn([speed],[callback]).html
#define IDH_1066	1066	; fadeOut([speed],[callback]) 简单动画\fadeOut([speed],[callback]).html
#define IDH_1067	1067	; fadeToggle([speed],[callback]) 简单动画\fadeToggle([speed],[callback]).html
#define IDH_1068	1068	; hide([speed],[callback]) 简单动画\hide([speed],[callback]).html
#define IDH_1069	1069	; show([speed],[callback]) 简单动画\show([speed],[callback]).html
#define IDH_1070	1070	; slideDown([speed],[callback]) 简单动画\slideDown([speed],[callback]).html
#define IDH_1071	1071	; slideToggle([speed],[callback]) 简单动画\slideToggle([speed],[callback]).html
#define IDH_1072	1072	; slideUp([speed],[callback]) 简单动画\slideUp([speed],[callback]).html
#define IDH_1073	1073	; toggle([speed],[callback]) 简单动画\toggle([speed],[callback]).html
#define IDH_1059	1059	; first() 文档处理\查找元素\first().html
#define IDH_1060	1060	; last() 文档处理\查找元素\last().html
#define IDH_1061	1061	; next() 文档处理\查找元素\next().html
#define IDH_1062	1062	; parent([num]) 文档处理\查找元素\parent([num]).html
#define IDH_1063	1063	; prev() 文档处理\查找元素\prev().html
#define IDH_1054	1054	; clone() 文档处理\复制元素\clone().html
#define IDH_1048	1048	; append(para) 文档处理\内部插入\append(para).html
#define IDH_1049	1049	; appendTo(para) 文档处理\内部插入\appendTo(para).html
#define IDH_1050	1050	; prepend(para) 文档处理\内部插入\prepend(para).html
#define IDH_1051	1051	; prependTo(para) 文档处理\内部插入\prependTo(para).html
#define IDH_1052	1052	; empty() 文档处理\删除\empty().html
#define IDH_1053	1053	; remove() 文档处理\删除\remove().html
#define IDH_1055	1055	; after(para) 文档处理\外部插入\after(para).html
#define IDH_1056	1056	; before(para) 文档处理\外部插入\before(para).html
#define IDH_1057	1057	; insertAfter(para) 文档处理\外部插入\insertAfter(para).html
#define IDH_1058	1058	; insertBefore(para) 文档处理\外部插入\insertBefore(para).html
#define IDH_1033	1033	; zlib.static.getKey(e) 事件\访问键盘\zlib.static.getKey(e).html
#define IDH_1034	1034	; zlib.static.preventDefault(e) 事件\默认动作\zlib.static.preventDefault(e).html
#define IDH_1032	1032	; zlib.static.getTarget(e) 事件\目标元素\zlib.static.getTarget(e).html
#define IDH_1029	1029	; bindEvent(eventType,callback) 事件\事件绑定\bindEvent(eventType,callback).html
#define IDH_1030	1030	; isMouseLeaveOrEnter(e) 事件\事件绑定\isMouseLeaveOrEnter(e).html
#define IDH_1031	1031	; mouseHover(fn1,fn2) 事件\事件绑定\mouseHover(fn1,fn2).html
#define IDH_1028	1028	; zlib.static.stopBubble(e) 事件\事件冒泡\zlib.static.stopBubble(e).html
#define IDH_1000	1000	; zlib.static.ajax(options) ajax\zlib.static.ajax(options).html
